# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '图片加载优化' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'Masonry', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.2.0'
  # Pods for 图片加载优化

  target '图片加载优化Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '图片加载优化UITests' do
    # Pods for testing
  end

end
